'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {DraftSync,SaveError,type Draft} from '@/lib/draft-sync';
import {FIRST_RESULT,REVISED_RESULT,type ActivityData,type ActivitySnapshot} from '@/lib/activity/types';
import {activityAction,useActivity} from './useActivity';
import {ResultText} from './ResultText';

function Snapshot({snapshot,fields}:{snapshot:ActivitySnapshot;fields:NonNullable<ActivityData['form']>['fields']}){return <div className="space-y-5">{fields.filter(f=>f.stage==='before').map(f=><div key={f.id}><h4 className="mb-1 text-xs font-medium text-ink-2">{f.question}</h4><ResultText text={snapshot.answers[f.id]??''}/></div>)}<div className="border-t border-line pt-4"><h4 className="mb-2 text-xs font-medium text-ink-2">첫 결과 · 텍스트 또는 링크</h4><ResultText text={snapshot.result}/></div></div>}
export function ActivityWorkspace({id,reviewUser}:{id:string;reviewUser?:string}){
 const {data,error,refresh}=useActivity(id);
 const [answers,setAnswers]=useState<Record<string,string>>({}),[ready,setReady]=useState(false),[tab,setTab]=useState(reviewUser?'peers':'mine');
 const [pending,setPending]=useState<{intent:'share'|'complete';version:string}|null>(null);
 const [save,setSave]=useState('idle'),[saveError,setSaveError]=useState(''),[localError,setLocalError]=useState(false);
 const [selected,setSelected]=useState(''),[feedback,setFeedback]=useState(''),[feedbackDirty,setFeedbackDirty]=useState(false),[feedbackError,setFeedbackError]=useState(''),[busy,setBusy]=useState(false);
 const controller=useRef<DraftSync|null>(null),hydrated=useRef(''),localKey=useRef('');
 useEffect(()=>{
  if(!data?.form)return;
  const signature=JSON.stringify(data.form.fields);if(hydrated.current===signature)return;
  controller.current?.stop();hydrated.current=signature;const key=`creai_activity:${id}:${data.viewer.id}`;localKey.current=key;
  let local:Draft|null=null;
  try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(parsed.answers&&typeof parsed.version==='string'&&typeof parsed.submit==='boolean'&&Object.values(parsed.answers).every(v=>typeof v==='string'))local=parsed;}}catch{setLocalError(true)}
  const initial:Draft={answers:Object.fromEntries([...data.form.fields.map(f=>f.id),FIRST_RESULT,REVISED_RESULT].map(k=>[k,local?.answers[k]??data.mine.answers[k]??''])),version:local?.version??data.mine.version,submit:local?.submit??false,intent:local?.intent};
  setAnswers(initial.answers);setReady(true);
  const sync=new DraftSync(initial,{
   write(d){try{localStorage.setItem(key,JSON.stringify(d));setLocalError(false)}catch{setLocalError(true)}},
   clear(){try{localStorage.removeItem(key)}catch{}},
   async send(draft){const res=await fetch(`/api/activities/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({answers:draft.answers,version:draft.version,action:draft.submit?draft.intent??'share':'save'}),signal:AbortSignal.timeout(10000)});const r=await res.json();if(!res.ok)throw new SaveError(r.error,r.version,res.status>=400&&res.status<500&&res.status!==429);void refresh();return r;},
   status(s,message){setSave(s);setSaveError(message??'');if(s==='failed')setPending(null)},submitted(){void refresh()},
  });controller.current=sync;if(local&&data.session.activityStatus==='open')sync.restore();
 },[data,id,refresh]);
 useEffect(()=>{if(pending&&data&&data.mine.version!==pending.version&&(pending.intent==='share'?data.mine.firstSharedAt:data.mine.completedAt))setPending(null)},[data,pending]);
 useEffect(()=>{if(reviewUser&&data&&!selected){const peer=data.peers.find(p=>p.userId===reviewUser);if(peer)choosePeer(peer)}},[data,reviewUser,selected]);
 useEffect(()=>()=>{controller.current?.stop()},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(localError||feedbackDirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[localError,feedbackDirty]);
 function submit(intent:'share'|'complete'){if(!data)return;setPending({intent,version:data.mine.version});controller.current?.edit(answers,true,intent)}
 function edit(key:string,value:string){const next={...answers,[key]:value};setAnswers(next);controller.current?.edit(next)}
 function choosePeer(peer:NonNullable<ActivityData>['peers'][number]){setSelected(peer.id);let value=peer.feedback.find(f=>f.authorId===data?.viewer.id)?.text??'';try{value=localStorage.getItem(`creai_feedback:${id}:${data?.viewer.id}:${peer.id}`)??value}catch{}setFeedback(value);setFeedbackDirty(false);setFeedbackError('')}
 function editFeedback(value:string){setFeedback(value);setFeedbackDirty(true);try{localStorage.setItem(`creai_feedback:${id}:${data?.viewer.id}:${selected}`,value)}catch{setFeedbackError('초안을 기기에 저장할 수 없습니다. 창을 닫기 전에 피드백을 저장해 주세요.')}}
 async function sendFeedback(){setBusy(true);setFeedbackError('');try{await activityAction(id,{action:'feedback',target:selected,text:feedback});try{localStorage.removeItem(`creai_feedback:${id}:${data?.viewer.id}:${selected}`)}catch{}setFeedbackDirty(false);setFeedbackError('피드백을 저장했습니다.');await refresh()}catch(e){setFeedbackError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setBusy(false)}}
 if(!data)return <div className="card p-8" role="status">{error||'활동을 불러오는 중…'}{error&&<button className="btn ml-3" onClick={()=>void refresh()}>다시 불러오기</button>}</div>;
 const open=data.session.activityStatus==='open',shared=!!data.mine.firstSharedAt,complete=!!data.mine.completedAt;
 const field=(f:{id:string;question:string},readOnly=false)=><label className="block" key={f.id}><span className="mb-2 block text-sm font-medium whitespace-pre-line">{f.question}</span><textarea className="field min-h-28 resize-y" maxLength={30000} value={answers[f.id]??''} onChange={e=>edit(f.id,e.target.value)} readOnly={readOnly||!open||!!pending} placeholder="한두 문장으로 짧게 남겨도 괜찮습니다."/></label>;
 const peer=data.peers.find(p=>p.id===selected);
 return <div className="space-y-6">
  <header><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><Link className="text-sm text-ink-2" href={data.viewer.admin?`/routes/admin/run/${id}`:"/routes/home"}>{data.viewer.admin?"← 운영 화면":"← 회차 목록"}</Link><Link className="btn" target="_blank" href={`/routes/deck?session=${id}`}>장표 보기 ↗</Link></div><p className="text-sm text-accent-strong">{data.session.studyName} · {data.session.weekNo===0?'리허설':`${data.session.weekNo}주차`}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">인클래스 활동</h1><div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span className="rounded-full bg-accent-soft px-3 py-1 text-accent-strong">{open?'작성 가능':data.session.activityStatus==='closed'?'마감 · 기록 보기':'시작 전 · 미리보기'}</span><span className="text-ink-2" role="status">{save==='saving'?'저장 중…':save==='failed'?'저장하지 못했습니다':save==='saved'?'자동 저장됨':''}</span></div></header>
  {error&&<p role="alert" className="card p-4 text-sm">연결을 확인하고 있습니다. 작성 중인 내용은 유지됩니다. {error}</p>}
  {!open&&<div className="card p-4 text-sm text-ink-2">{data.session.activityStatus==='closed'?'활동이 마감되었습니다. 내 초안과 제출물, 받은 피드백을 확인할 수 있습니다.':'운영진이 활동을 열면 이 화면에서 바로 작성할 수 있습니다.'}</div>}
  {!data.form?<div className="card p-8">활동 질문을 준비 중입니다. 등록되면 이 화면에 표시됩니다.</div>:<>
   <details className="card p-5" open={!shared}><summary className="cursor-pointer font-semibold text-sm">오늘 할 일과 진행 안내</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-ink-2">{data.form.topicMd}</p><p className="mt-3 text-xs text-ink-2">AI 작업은 익숙한 도구에서 진행하고, 여기에는 요청·결과·피드백을 남깁니다.</p></details>
   <ol className="grid grid-cols-3 gap-2 text-sm" aria-label="내 진행 상태">{['첫 결과 작성','동료 피드백','수정 제출'].map((label,i)=><li key={label} className={`border-t-2 py-3 ${i===(complete?2:shared?1:0)?'border-accent font-semibold text-accent-strong':'border-line text-ink-2'}`}>{i+1}. {label}{i===2&&complete?' ✓':''}</li>)}</ol>
   <div className="flex gap-2 border-b border-line pb-3" role="tablist" aria-label="활동 보기"><button role="tab" aria-selected={tab==='mine'} className={`btn ${tab==='mine'?'btn-primary':''}`} onClick={()=>setTab('mine')}>내 작업</button><button role="tab" aria-selected={tab==='peers'} className={`btn ${tab==='peers'?'btn-primary':''}`} onClick={()=>setTab('peers')}>동료 결과 {data.peers.length}</button></div>
   {tab==='mine'?<div className="space-y-6">
    {(saveError||localError)&&<div role="alert" className="card border-amber-300 p-4 text-sm"><p>{saveError||'이 기기에 초안을 보관할 수 없습니다. 저장됨을 확인한 뒤 이동해 주세요.'}</p>{open&&<button className="btn mt-3" disabled={!!pending} onClick={()=>submit(shared?'complete':'share')}>내용 확인 후 다시 제출</button>}<button className="btn mt-3 ml-2" onClick={()=>{const blob=new Blob([JSON.stringify(answers,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='내-활동-초안.json';a.click();URL.revokeObjectURL(url)}}>초안 내려받기</button></div>}
    <section className="card p-5 sm:p-7"><div className="mb-6 flex justify-between gap-3"><h2 className="text-lg font-semibold">1. 첫 결과</h2>{shared&&<span className="text-xs text-accent-strong">공유본 보존됨</span>}</div>{shared&&data.mine.firstSnapshot?<Snapshot snapshot={data.mine.firstSnapshot} fields={data.form.fields}/>:<div className="space-y-6">{data.form.fields.filter(f=>f.stage==='before').map(f=>field(f))}{field({id:FIRST_RESULT,question:'첫 결과 · 텍스트 또는 링크'})}<p className="text-xs text-ink-2">공유할 자료만 붙여 주세요. 외부 링크는 동료가 열 수 있는지 확인해 주세요.</p>{open&&<button className="btn btn-primary" disabled={!ready||save==='saving'||!!pending} onClick={()=>submit('share')}>첫 결과 공유하기</button>}<p className="text-xs text-ink-2">공유하면 첫 답변과 결과가 보존됩니다. 이후 수정은 아래에 남깁니다.</p></div>}</section>
    {shared&&<>
     <section className="card p-5 sm:p-7"><h2 className="text-lg font-semibold">2. 받은 피드백</h2>{data.mine.feedback.length?<div className="mt-4 space-y-4">{data.mine.feedback.map(f=><div key={f.id} className="border-l-2 border-accent pl-4"><p className="mb-1 text-xs font-medium text-ink-2">{f.name}</p><ResultText text={f.text}/></div>)}</div>:<p className="mt-3 text-sm text-ink-2">아직 앱에 남긴 피드백이 없습니다. 말로 받은 의견도 수정에 반영할 수 있습니다.</p>}<button className="btn mt-4" onClick={()=>setTab('peers')}>{open?'동료 결과 보고 피드백 남기기 →':'동료 결과 보기 →'}</button></section>
     <section className="card p-5 sm:p-7"><h2 className="mb-2 text-lg font-semibold">3. 수정 결과</h2><p className="mb-6 text-sm text-ink-2">{open?'고칠 점 하나를 정하고 AI에게 다시 맡겨 보세요.':'마지막으로 저장한 수정 결과와 답변입니다.'}</p><div className="space-y-6">{field({id:REVISED_RESULT,question:'다시 받은 결과 · 텍스트 또는 링크'})}{data.form.fields.filter(f=>f.stage==='after').map(f=>field(f))}</div><div className="mt-6 flex flex-wrap items-center gap-3">{open&&<button className="btn btn-primary" disabled={save==='saving'||!!pending} onClick={()=>submit('complete')}>{complete?'수정본 다시 제출':'수정 결과 제출하기'}</button>}{complete&&<p role="status" className="text-sm text-accent-strong">제출 완료 · 내 활동 기록에 보관됩니다.</p>}</div></section>
    </>}
   </div>:<section className="space-y-4">{!data.session.sharingOpen?<div className="card p-6 text-sm">운영진이 공유를 열면 동료의 첫 결과를 볼 수 있습니다.</div>:!data.peers.length?<div className="card p-6 text-sm">아직 공유된 동료 결과가 없습니다. 먼저 내 결과를 공유하고 잠시 기다려 주세요.</div>:<><div className="flex flex-wrap gap-2">{data.peers.map(p=><button key={p.id} className={`btn ${selected===p.id?'btn-primary':''}`} onClick={()=>choosePeer(p)}>{p.name}{p.completedAt?' · 수정 완료':''}</button>)}</div>{peer?<article className="card p-5 sm:p-7"><h2 className="mb-6 text-lg font-semibold">{peer.name}의 첫 결과</h2><Snapshot snapshot={peer.snapshot} fields={data.form.fields}/>{peer.completedAt&&<details className="mt-6 border-t border-line pt-4"><summary className="cursor-pointer text-sm font-semibold">수정한 결과 보기</summary><div className="mt-3"><ResultText text={peer.revisedResult}/>{data.form.fields.filter(f=>f.stage==='after').map(f=><div key={f.id} className="mt-4"><p className="text-xs text-ink-2">{f.question}</p><ResultText text={peer.reflection[f.id]??''}/></div>)}</div></details>}<div className="mt-7 border-t border-line pt-5"><label className="text-sm font-semibold" htmlFor="peer-feedback">실제로 쓰려면 무엇을 하나 고치면 좋을까요?</label><textarea id="peer-feedback" className="field mt-3 min-h-28" maxLength={5000} value={feedback} readOnly={!open} onChange={e=>editFeedback(e.target.value)} placeholder="좋았던 점과 고칠 점을 구체적으로 남겨 주세요."/>{open&&<button className="btn btn-primary mt-3" disabled={busy||!feedback.trim()} onClick={()=>void sendFeedback()}>피드백 저장</button>}{feedbackError&&<p role="status" className="mt-3 text-sm">{feedbackError}</p>}</div></article>:<p className="p-5 text-sm text-ink-2">피드백할 동료를 선택해 주세요.</p>}</>}<button className="btn" onClick={()=>setTab('mine')}>← 내 작업으로 돌아가기</button></section>}
  </>}
 </div>;
}
