import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {prisma} from '../lib/prisma';
import {readActivity,mutateActivity} from '../lib/activity/service';
import {FIRST_RESULT,REVISED_RESULT} from '../lib/activity/types';
import {controlSession} from '../lib/session-control';
if(process.env.DATABASE_URL!=='postgresql://study_local@127.0.0.1:55439/study_test')throw Error('Isolated local database required');
after(()=>prisma.$disconnect());
test('six members complete an activity with snapshots, feedback, conflicts, recording independence and archive access',async()=>{
 const prefix='activity-test';
 await prisma.studySession.deleteMany({where:{id:{startsWith:prefix}}});
 await prisma.study.deleteMany({where:{id:prefix}});await prisma.user.deleteMany({where:{id:{startsWith:prefix}}});
 const users=await Promise.all(Array.from({length:8},(_,i)=>prisma.user.create({data:{id:`${prefix}-user-${i}`,email:`activity-${i}@example.invalid`,name:`테스트 참가자 ${i}`,roles:i===7?['admin']:['participant']}})));
 const members=users.slice(0,6).map(u=>({id:u.id,roles:['participant']}));const admin={id:users[7].id,roles:['admin']};const outsider={id:users[6].id,roles:['participant']};
 await prisma.study.create({data:{id:prefix,name:'활동 테스트',members:{create:members.map(u=>({userId:u.id}))}}});
 const id=`${prefix}-session`;
 await prisma.studySession.create({data:{id,studyId:prefix,weekNo:1,date:new Date(),formDef:{create:{topicMd:'테스트 활동',fields:{create:[{id:`${prefix}-before`,order:1,question:'첫 질문',stage:'before'},{id:`${prefix}-after`,order:2,question:'수정 이유',stage:'after'}]}}}}});
 const v=(i:number)=>({[`${prefix}-before`]:`과업 ${i}`,[`${prefix}-after`]:'',[FIRST_RESULT]:`첫 결과 ${i}`,[REVISED_RESULT]:''});
 assert.equal((await readActivity(id,admin)).people.length,6);
 assert.equal(await prisma.submission.count({where:{formDef:{sessionId:id}}}),0,'preview creates no submissions');
 await assert.rejects(readActivity(id,outsider));await assert.rejects(mutateActivity(id,members[0],{action:'open'}));
 await assert.rejects(mutateActivity(id,members[0],{action:'save',version:'new',answers:v(0)}));
 await mutateActivity(id,admin,{action:'open'});
 assert.equal((await prisma.studySession.findUniqueOrThrow({where:{id}})).recordingState,'idle');
 const saved=await Promise.all(members.map((u,i)=>mutateActivity(id,u,{action:'save',version:'new',answers:v(i)})));
 for(const [i,u] of members.entries())await mutateActivity(id,u,{action:'share',version:('version' in saved[i]?saved[i].version:'new'),answers:v(i)});
 const first=await readActivity(id,members[0]);assert.equal(first.peers.length,5);assert.equal(first.mine.firstSnapshot?.result,'첫 결과 0');
 await mutateActivity(id,members[1],{action:'feedback',target:first.mine.id,text:'검증 기준을 명확히 해 주세요.'});
 await assert.rejects(mutateActivity(id,outsider,{action:'feedback',target:first.mine.id,text:'접근 시도'}));
 const own=await readActivity(id,members[0]);assert.equal(own.mine.feedback.length,1);
 assert.equal((await readActivity(id,members[2])).peers.find(p=>p.id===first.mine.id)?.feedback.length,0,'other peer cannot read private feedback');
 await assert.rejects(mutateActivity(id,members[0],{action:'save',version:own.mine.version,answers:{...v(0),[FIRST_RESULT]:'덮어쓰기'}}));
 const finalAnswers={...v(0),[`${prefix}-after`]:'기준을 추가했습니다.',[REVISED_RESULT]:'수정 결과'};
 const result=await mutateActivity(id,members[0],{action:'complete',version:own.mine.version,answers:finalAnswers});
 const retry=await mutateActivity(id,members[0],{action:'complete',version:own.mine.version,answers:finalAnswers});assert.equal('version' in retry&&retry.version,'version' in result&&result.version);
 await assert.rejects(mutateActivity(id,members[0],{action:'save',version:own.mine.version,answers:{...finalAnswers,[REVISED_RESULT]:'오래된 탭'}}));
 await mutateActivity(id,admin,{action:'sharing',open:false});assert.equal((await readActivity(id,members[0])).peers.length,0);await assert.rejects(mutateActivity(id,members[1],{action:'feedback',target:first.mine.id,text:'닫힌 공유'}));
 await mutateActivity(id,admin,{action:'sharing',open:true});
 const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';await controlSession(id,{action:'start',recorderKey:key},admin.id);await controlSession(id,{action:'end',recorderKey:key},admin.id);
 assert.equal((await readActivity(id,members[0])).session.activityStatus,'open','ending audio does not close activity');
 const pending=await readActivity(id,members[1]);await mutateActivity(id,members[1],{action:'complete',version:pending.mine.version,answers:{...v(1),[`${prefix}-after`]:'개선',[REVISED_RESULT]:'최종'}});
 await mutateActivity(id,admin,{action:'close'});const archive=await readActivity(id,members[0]);assert.equal(archive.mine.firstSnapshot?.result,'첫 결과 0');assert.equal(archive.mine.answers[REVISED_RESULT],'수정 결과');assert.equal(archive.mine.feedback.length,1);
 await assert.rejects(mutateActivity(id,members[0],{action:'save',version:archive.mine.version,answers:finalAnswers}));
 await mutateActivity(id,admin,{action:'reopen'});assert.equal((await readActivity(id,members[0])).session.activityStatus,'open');
 await prisma.studySession.delete({where:{id}});await prisma.study.delete({where:{id:prefix}});await prisma.user.deleteMany({where:{id:{startsWith:prefix}}});
});
