// Run only against the disposable local database, never the configured Supabase.
import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { prisma } from '../lib/prisma';
import { register, authenticate, issuePasswordSetup, completePasswordSetup } from '../lib/password-auth';
import { consumeAttempt } from '../lib/auth-rate-limit';
const password = 'correct horse battery staple';
if (!process.env.DATABASE_URL?.startsWith('postgresql://study_local@127.0.0.1:55439/study_test')) throw Error('Local test database required');
after(() => prisma.$disconnect());
test('password accounts, legacy migration, and throttling', async () => {
  await prisma.user.deleteMany({where:{email:{endsWith:'@auth-test.invalid'}}});
  await prisma.authRateLimit.deleteMany();
  await assert.rejects(register({name:'Test',email:'new@auth-test.invalid',password,agreed:false}));
  await register({name:'Test',email:' New@auth-test.invalid ',password,agreed:true,roles:['admin']});
  const user = await authenticate({email:'NEW@auth-test.invalid',password});
  assert.ok(user);
  assert.equal('passwordHash' in user, false);
  const row = await prisma.user.findUniqueOrThrow({where:{id:user.id}});
  assert.deepEqual(row.roles, ['participant']);
  assert.ok(row.consentedAt);
  assert.notEqual(row.passwordHash, password);
  assert.equal(await authenticate({email:row.email,password:'wrong password which is long'}), null);
  await assert.rejects(register({name:'Again',email:'NEW@auth-test.invalid',password,agreed:true}));
  process.env.ADMIN_EMAILS='reserved@auth-test.invalid';
  await assert.rejects(register({name:'Fake admin',email:'reserved@auth-test.invalid',password,agreed:true}));
  const legacy = await prisma.user.create({data:{email:'legacy@auth-test.invalid',name:'Existing',roles:['participant','admin']}});
  await assert.rejects(register({name:'Takeover',email:legacy.email,password,agreed:true}));
  assert.equal(await authenticate({email:legacy.email,password}), null);
  const oldLink = await issuePasswordSetup(legacy.email);
  const link = await issuePasswordSetup(legacy.email);
  await assert.rejects(completePasswordSetup({token:oldLink,password,agreed:true}));
  await assert.rejects(completePasswordSetup({token:link,password,agreed:false}));
  const results = await Promise.allSettled([1,2].map(()=>completePasswordSetup({token:link,password,agreed:true})));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const migrated = await prisma.user.findUniqueOrThrow({where:{id:legacy.id}});
  assert.deepEqual(migrated.roles,['participant','admin']);
  assert.ok(migrated.consentedAt);
  assert.equal(migrated.authVersion,1);
  assert.ok(await authenticate({email:legacy.email,password}));
  const expired = await issuePasswordSetup(legacy.email);
  await prisma.verificationToken.updateMany({where:{identifier:legacy.id},data:{expires:new Date(0)}});
  await assert.rejects(completePasswordSetup({token:expired,password,agreed:true}));
  const attempts=await Promise.all(Array.from({length:12},()=>consumeAttempt('test-limit',5)));
  assert.equal(attempts.filter(Boolean).length,5);
});
