import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {prisma} from '../lib/prisma';
import {readActivity,mutateActivity} from '../lib/activity/service';
import {FIRST_RESULT,REVISED_RESULT} from '../lib/activity/types';
import {listEvents,practiceTurn,PRACTICE_TURN_LIMIT} from '../lib/practice/agent';
import {prepareCommentary,readCommentary,summarizeParticipant} from '../lib/practice/commentary';
if(process.env.DATABASE_URL!=='postgresql://study_local@127.0.0.1:55439/study_test')throw Error('Isolated local database required');
after(()=>prisma.$disconnect());
// Seven-byte chunks split multi-byte Korean characters and SSE frames across reads.
const sse=(events:{type:string}[])=>{const bytes=new TextEncoder().encode(events.map(e=>`event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`).join(''));return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close()}}))};
const answer=(text:string)=>sse([{type:'response.created'},{type:'response.web_search_call.searching'},...[...text].map(ch=>({type:'response.output_text.delta',delta:ch})),
 {type:'response.completed',response:{id:'resp_test',model:'gpt-6-luna',status:'completed',usage:{input_tokens:10,output_tokens:5},output:[{type:'reasoning'},{type:'web_search_call',action:{query:'시장 규모 근거'}},{type:'message',content:[{type:'output_text',text,annotations:[{type:'url_citation',url:'https://source.example',title:'통계 자료'}]}]}]}}] as {type:string}[]);
const drain=async(stream:ReadableStream<Uint8Array>)=>(await new Response(stream).text()).trim().split('\n').map(l=>JSON.parse(l));
const structured=(value:unknown)=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(value)}]}]});
test('practice turns, result milestones, summaries, commentary and spotlight stay scoped',async()=>{
 const prefix='practice-test';
 await prisma.studySession.deleteMany({where:{id:{startsWith:prefix}}});
 await prisma.study.deleteMany({where:{id:prefix}});await prisma.user.deleteMany({where:{id:{startsWith:prefix}}});
 const users=await Promise.all(Array.from({length:5},(_,i)=>prisma.user.create({data:{id:`${prefix}-user-${i}`,email:`practice-${i}@example.invalid`,name:`테스트 참가자 ${i}`,roles:i===4?['admin']:['participant']}})));
 const members=users.slice(0,3).map(u=>({id:u.id,roles:['participant']})),outsider={id:users[3].id,roles:['participant']},admin={id:users[4].id,roles:['admin']};
 await prisma.study.create({data:{id:prefix,name:'실습 테스트',members:{create:members.map(u=>({userId:u.id}))}}});
 const id=`${prefix}-session`,goal=`${prefix}-goal`,reflect=`${prefix}-reflect`;
 await prisma.studySession.create({data:{id,studyId:prefix,weekNo:1,date:new Date(),formDef:{create:{topicMd:'시장 조사 위임',agentMd:'과제: 국내 시장 규모 조사',agentWebSearch:true,fields:{create:[{id:goal,order:1,question:'목표와 기준',stage:'before'},{id:reflect,order:2,question:'배운 점',stage:'after'}]}}}}});
 const values=(first='',revised='')=>({[goal]:'출처가 있는 시장 규모',[reflect]:revised?'근거를 먼저 요구한다':'',[FIRST_RESULT]:first,[REVISED_RESULT]:revised});
 const originalFetch=global.fetch,originalKey=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='test';
 const calls:{model:string;reasoning:{effort:string};store:boolean;stream?:boolean;tools?:unknown;instructions:string;input:unknown;text?:{format:{name:string;strict:boolean}}}[]=[];
 const fake=(respond:(body:typeof calls[number])=>Response)=>{global.fetch=async(_url,init)=>{const body=JSON.parse(String(init?.body));calls.push(body);return respond(body)}};
 try{
  await assert.rejects(practiceTurn(id,members[0],{text:'시작'}),/활동이 열려/);
  await mutateActivity(id,admin,{action:'open'});
  const draft=await mutateActivity(id,members[0],{action:'save',version:'new',answers:values()});
  fake(()=>answer('시장 규모는 3조 원입니다.'));
  const lines=await drain(await practiceTurn(id,members[0],{text:'출처 없이 시장 규모를 정리해 줘'}));
  assert.equal(lines.filter(l=>l.t==='delta').map(l=>l.v).join(''),'시장 규모는 3조 원입니다.');
  assert.ok(lines.some(l=>l.t==='status'&&l.v==='search'));
  const done=lines[lines.length-1];
  assert.equal(done.t,'done');assert.equal(done.request.seq,1);assert.equal(done.response.seq,2);
  assert.deepEqual(done.response.sources,[{url:'https://source.example',title:'통계 자료'}]);assert.deepEqual(done.response.searches,['시장 규모 근거']);
  assert.equal(calls[0].model,'gpt-6-luna');assert.equal(calls[0].reasoning.effort,'high');assert.equal(calls[0].store,false);assert.equal(calls[0].stream,true);
  assert.deepEqual(calls[0].tools,[{type:'web_search'}]);
  assert.ok(calls[0].instructions.includes('과제: 국내 시장 규모 조사'),'agent task is in instructions');
  assert.ok(calls[0].instructions.includes('출처가 있는 시장 규모'),'participant-written goal is in instructions');
  assert.deepEqual(calls[0].input,[{role:'user',content:'출처 없이 시장 규모를 정리해 줘'}]);
  await drain(await practiceTurn(id,members[0],{text:'근거 자료를 붙여서 다시 써 줘'}));
  assert.deepEqual((calls[1].input as {role:string}[]).map(m=>m.role),['user','assistant','user'],'history is resent from the record');
  fake(()=>new Response('upstream down',{status:500}));
  const failed=await drain(await practiceTurn(id,members[0],{text:'실패할 요청'}));
  assert.equal(failed[0].t,'error');
  assert.equal(await prisma.practiceEvent.count({where:{sessionId:id,userId:members[0].id}}),4,'a failed request leaves no dangling record');
  await assert.rejects(listEvents(id,members[1],members[0].id),/운영진만/);
  await assert.rejects(listEvents(id,outsider),/접근할 수 없습니다/);
  assert.equal((await listEvents(id,admin,members[0].id)).events.length,4);
  assert.equal((await listEvents(id,members[0])).remaining,PRACTICE_TURN_LIMIT-2);
  await mutateActivity(id,members[0],{action:'share',version:'version' in draft?draft.version:'new',answers:values('채택한 결과')});
  const milestone=await prisma.practiceEvent.findFirstOrThrow({where:{sessionId:id,userId:members[0].id},orderBy:{seq:'desc'}});
  assert.deepEqual([milestone.seq,milestone.kind,milestone.text,(milestone.meta as {target:string}).target],[5,'result','채택한 결과','first']);
  fake(()=>answer('근거부터 찾았습니다.'));
  await drain(await practiceTurn(id,members[1],{text:'근거부터 찾아줘'}));
  calls.length=0;
  fake(body=>{
   const input=JSON.parse(String(body.input));
   if(body.text?.format.name==='practice_summary'){const first=input.events[0];return structured({goal:'시장 규모 정리',approach:'결과를 받고 근거를 요구했다.',turningPoints:[{seq:first.seq,observed:'첫 요청',quote:first.text.slice(0,6)},{seq:first.seq,observed:'만든 인용',quote:'기록에 없는 문장'}],resultState:'공유함',interpretation:'근거 요구 시점이 다르다.',askParticipant:[]})}
   const keys=input.participants.map((p:{key:string})=>p.key);
   return structured({commonBlockers:[{text:'처음에는 근거 없이 요청했다.',cases:[{participant:keys[0],seq:1,note:'첫 요청'}]}],contrasts:[{text:'근거를 요구한 시점이 다르다.',cases:keys.map((k:string)=>({participant:k,seq:1,note:'첫 요청'}))}],verification:[],discussion:[{question:'언제 근거를 요구할까요?',why:'시점이 달랐다.',cases:[{participant:'p9',seq:1,note:'없는 참가자'}]}]});
  });
  assert.equal(await prepareCommentary(id),0);
  const summaryCalls=calls.filter(c=>c.text?.format.name==='practice_summary'),commentaryCall=calls.find(c=>c.text?.format.name==='practice_commentary');
  assert.equal(summaryCalls.length,2);assert.ok(commentaryCall);
  assert.equal(summaryCalls[0].model,'gpt-6-luna');assert.equal(summaryCalls[0].reasoning.effort,'high');assert.equal(summaryCalls[0].text?.format.strict,true);
  assert.ok(!String(commentaryCall.input).includes('테스트 참가자'),'names never reach the model');
  const view=await readCommentary(id);
  const p0=view.people.find(p=>p.id===members[0].id)!;
  assert.equal(view.people.length,2);assert.equal(p0.turns,2);assert.equal(p0.summary?.throughSeq,5);
  assert.equal(p0.summary?.data.turningPoints.length,1,'invented quotes are dropped');
  assert.deepEqual(new Set(view.commentary?.data.contrasts[0].cases.map(c=>c.userId)),new Set([members[0].id,members[1].id]));
  assert.equal(view.commentary?.data.discussion.length,0,'cases for unknown participants are dropped');
  assert.equal(view.commentary?.stale,false);
  calls.length=0;await summarizeParticipant(id,members[0].id);assert.equal(calls.length,0,'a fresh summary is not regenerated');
  fake(()=>answer('추가 응답'));
  await drain(await practiceTurn(id,members[1],{text:'표로 정리해 줘'}));
  const later=await readCommentary(id);
  assert.equal(later.commentary?.stale,true);
  const p1=later.people.find(p=>p.id===members[1].id)!;assert.equal(p1.latestSeq-(p1.summary?.throughSeq??0),2);
  await assert.rejects(mutateActivity(id,members[1],{action:'spotlight',userId:members[0].id,from:1,to:2}),/운영진만/);
  await assert.rejects(mutateActivity(id,admin,{action:'spotlight',userId:members[0].id,from:1,to:30}),/1~20/);
  await assert.rejects(mutateActivity(id,admin,{action:'spotlight',userId:members[2].id,from:1,to:2}),/찾을 수 없습니다/);
  await mutateActivity(id,admin,{action:'spotlight',userId:members[0].id,from:1,to:2});
  const peer=await readActivity(id,members[2]);
  assert.equal(peer.spotlight?.name,'테스트 참가자 0');assert.deepEqual(peer.spotlight?.events.map(e=>e.seq),[1,2],'peers see only the chosen range');
  assert.equal((await readActivity(id,admin)).people.find(p=>p.id===members[0].id)?.turns,2);
  assert.equal((await readCommentary(id)).spotlight?.from,1);
  await mutateActivity(id,admin,{action:'spotlight',clear:true});
  assert.equal((await readActivity(id,members[2])).spotlight,null);
  await prisma.practiceEvent.createMany({data:Array.from({length:PRACTICE_TURN_LIMIT},(_,i)=>({sessionId:id,userId:members[2].id,seq:i+1,kind:'request',text:'x'}))});
  await assert.rejects(practiceTurn(id,members[2],{text:'한 번 더'}),/모두 사용/);
  await prisma.formDef.update({where:{sessionId:id},data:{agentMd:''}});
  await assert.rejects(practiceTurn(id,members[0],{text:'에이전트 없음'}),/준비되지 않았습니다/);
  assert.equal((await readActivity(id,members[0])).form?.agent,false);
 }finally{global.fetch=originalFetch;process.env.OPENAI_API_KEY=originalKey;}
});
