import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {prisma} from '../lib/prisma';
import {controlSession} from '../lib/session-control';
if(process.env.DATABASE_URL !== 'postgresql://study_local@127.0.0.1:55439/study_test')throw Error('Isolated local DB required');
after(()=>prisma.$disconnect());
test('recording owns lifecycle, cannot drop pending audio or close another session',async()=>{
 await prisma.studySession.deleteMany({where:{id:{startsWith:'recording-test-'}}});
 const a=await prisma.studySession.create({data:{id:'recording-test-a',studyId:'study-zero',weekNo:90,date:new Date()}});
 const b=await prisma.studySession.create({data:{id:'recording-test-b',studyId:'study-zero',weekNo:91,date:new Date()}});
 const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 await controlSession(a.id,{action:'start',recorderKey:key},'operator');
 await controlSession(a.id,{action:'start',recorderKey:key},'operator');
 await assert.rejects(controlSession(b.id,{action:'start',recorderKey:key},'operator'));
 await assert.rejects(controlSession(a.id,{action:'pause',recorderKey:'other'},'operator'));
 await assert.rejects(controlSession(a.id,{action:'next',recorderKey:key},'operator'));
 await controlSession(a.id,{action:'pause',recorderKey:key},'operator');
 assert.equal((await prisma.studySession.findUniqueOrThrow({where:{id:a.id}})).recordingState,'paused');
 await controlSession(a.id,{action:'resume',recorderKey:key},'operator');
 await prisma.recordingPart.create({data:{id:'recording-test-part',sessionId:a.id,path:'test.webm',mimeType:'audio/webm',bytes:10,recordedAt:new Date(),durationMs:1000}});
 await assert.rejects(controlSession(a.id,{action:'end',recorderKey:key},'operator'));
 await prisma.recordingPart.update({where:{id:'recording-test-part'},data:{uploadedAt:new Date()}});
 await controlSession(a.id,{action:'end',recorderKey:key},'operator');
 await controlSession(a.id,{action:'end',recorderKey:key},'operator');
 const ended=await prisma.studySession.findUniqueOrThrow({where:{id:a.id}});
 assert.equal(ended.status,'closed');assert.ok(ended.endedAt);assert.equal(ended.recordingState,'ended');
 await assert.rejects(controlSession(a.id,{action:'resume',recorderKey:key},'operator'));
 await prisma.studySession.deleteMany({where:{id:{startsWith:'recording-test-'}}});
});
