(() => {
const {SlideFrame,SlideTitle,BodyText,Connector}=window;
window.OT_SLIDES=[
{title:'우리가 지향하는 사람',note:'“와, 얘는 진짜 일도 잘하고 AI도 잘 쓴다”는 평가를 받는 사람을 지향합니다.\n4주는 그 성장에 필요한 이해와 판단의 기반을 만드는 기간입니다. 한 달 만에 완성되는 성과를 약속하는 것은 아닙니다.\n\n다음: 그러려면 무엇을 배워야 할까요?',render:()=> <SlideFrame dark label="FOUNDATION / ORIENTATION"><SlideTitle hero>AI 시대를 이끄는,<br/><em>압도적인 인재로.</em></SlideTitle><BodyText className="heroSub">그 성장의 기반을 다지는 4주.</BodyText><div className="coverRule"/></SlideFrame>},
{title:'두 가지 이해',note:'지식적 이해는 기술의 가능성과 한계, 변화의 의미를 읽고 AI 결과를 판단하는 근거입니다. 하지만 배경지식을 많이 아는 것만으로는 내 업무에서 실제로 무엇이 통하는지 확인할 수 없습니다. 직접 맡기고 검토하는 경험이 필요합니다.\n반대로 특정 도구의 사용법만 익혀도 당장 결과를 만들 수는 있습니다. 다만 그 결과를 언제 신뢰할 수 있는지, 실패가 왜 생겼는지, 새 모델이 나왔을 때 무엇을 바꿔야 하는지 판단할 근거는 약할 수 있습니다.\n그래서 지식은 활용의 판단 근거가 되고, 활용 경험은 지식을 검증하고 갱신하는 근거가 됩니다. 둘을 함께 기르는 것이 교육의 목적입니다.\n\n다음: 이 두 가지 이해를 네 주에 어떻게 배치할까요?',render:()=> <SlideFrame label="WHAT WE BUILD"><SlideTitle>변화를 이해하는 깊이와,<br/>AI를 활용하는 힘을 함께 기릅니다.</SlideTitle><div className="exhibit understanding"><Connector viewBox="0 0 1440 500" label="지식은 활용의 판단 근거가 되고, 활용은 지식을 실제 업무에서 검증하고 갱신한다. 지식만으로는 적용 여부를 검증하기 어렵고, 사용법만으로는 결과와 변화를 판단할 근거가 약하다."><path className="path" d="M305 90 C305 4 1135 4 1135 90"/><path className="path" d="M1135 420 C1135 490 305 490 305 420"/></Connector><div className="concept left"><h2>지식적 이해</h2><p>가능성과 한계를 해석하는 근거</p><div className="missingHalf"><span>활용 없이 지식만 쌓으면</span><p>내 일에서 무엇이 통하는지는<br/>직접 확인하지 못합니다.</p></div></div><div className="concept right"><h2>활용에 대한 이해</h2><p>내 일에 적용하고 검증하는 힘</p><div className="missingHalf"><span>이해 없이 사용법만 익히면</span><p>결과를 믿을지, 방식을 바꿀지<br/>판단할 근거가 약해집니다.</p></div></div><span className="relationLabel upper">판단의 근거 →</span><span className="relationLabel lower">← 경험으로 갱신</span></div></SlideFrame>},
{title:'4주의 학습 경로',note:'1주차는 현재의 frontier AI 도구들이 실제로 무엇까지 할 수 있는지 이해하고, 직접 사용을 시작할 최소한의 기반을 마련하는 과정입니다. 코딩 에이전트의 파일·실행 도구, 서브에이전트, 지침·스킬, 외부 연결 등을 가능성과 실제 사용 흐름에 연결합니다.\n2주차는 작은 요청을 넘어 더 큰 단위의 업무를 맡기고 협업하는 방법입니다. PRD는 목표와 완료 기준을 구체화하는 수단이며, 맥락과 자료·역할 분담·검토 지점을 설계하는 것이 핵심입니다.\n3주차는 계속 성장하는 활용 역량을 위한 마인드셋입니다. 어려운 일을 맡겨보고 실패에서 배우며, 모델이 좋아질 때 예전의 한계를 다시 확인하고 새로운 가능성을 발견합니다. 그 경험으로 자신의 활용 방식과 스킬을 갱신합니다.\n4주차는 새 지식을 계속 받아들이고 자기 레버리지로 해석할 배경지식입니다. 기술 원리·밸류체인·협상력을 통해 새로운 정보가 무엇을 바꾸고, 자기 일에 어떤 의미가 있는지 판단하는 기반을 만듭니다.\n1–3주는 활용 중심, 4주는 지식 중심이지만 두 가지 이해는 모든 주차에서 연결됩니다. 마지막 2주에는 개인 프로젝트를 병행하고 튜터의 피드백을 받습니다. 별도의 추가 2주 과정이 아닙니다.',render:()=> <SlideFrame label="THE FOUR WEEKS"><SlideTitle>AI를 쓰기 시작하는 데서,<br/>계속 더 잘 활용하는 사람으로.</SlideTitle><div className="exhibit roadmap"><div className="rail"/>{[
['1주','도구 이해',<>AI는 어디까지,<br/>나는 어디서부터?</>,<>최신 도구의 가능성과 한계,<br/>핵심 기능과 사용 흐름을 익혀<br/>직접 시작할 기반을 만듭니다.</>],
['2주','업무 설계',<>더 큰 일을,<br/>AI와 함께 하려면?</>,<>더 큰 업무의 목표를 정하고,<br/>맥락·역할·검토 지점을 설계해<br/>AI와 협업하는 법을 익힙니다.</>],
['3주','성장 마인드셋',<>모델이 좋아질 때,<br/>나도 더 잘 쓰려면?</>,<>어려운 일을 맡기며 배우고,<br/>새 모델의 가능성을 발견해<br/>활용 방식을 계속 갱신합니다.</>],
['4주','변화를 읽는 지식',<>새로운 지식을<br/>내 기회로 바꾸려면?</>,<>기술 원리·밸류체인·협상력으로<br/>새 정보를 해석하고,<br/>내 일에 주는 의미를 읽습니다.</>]
].map(([week,title,question,body])=><section className="week" key={week}><div className="weekMeta"><span className="weekNo">{week}</span><span className="weekName">{title}</span></div><span className="dot"/><h2>{question}</h2><p>{body}</p></section>)}<div className="projectRoadmapBand"><p>1–3주 활용 중심 · 4주 지식 중심</p><div><span>3–4주차 병행</span><strong>나만의 프로젝트 · 튜터링</strong></div></div></div></SlideFrame>},
{title:'우리가 배우는 방식',note:'잘된 결과뿐 아니라 막힌 지점을 가져와도 됩니다. 어려운 일을 맡기고, 어디에서 왜 막혔는지를 봅니다.\n모델 자체의 한계인지, 맥락이 부족했는지, 위임과 검토 구조가 문제였는지 구분하며 다음 시도를 바꿉니다.\n목표와 중요한 결과를 판단하는 책임은 사람에게 있습니다. 얻은 교훈은 다음 요청·지침·스킬에 반영합니다.\nOT에서는 구체적인 과제나 제출 형식을 확정하지 않습니다.',render:()=> <SlideFrame label="HOW WE LEARN"><SlideTitle>어려운 일을 맡겨보고,<br/>그 결과로 내 기준을 바꿉니다.</SlideTitle><div className="exhibit"><Connector label="맡겨보기, 결과 살피기, 기준 바꾸기에서 다음 시도로 돌아가는 학습 과정"><path className="path" d="M625 65 C802 65 815 194 932 194"/><path className="path" d="M1130 270 C1130 390 800 370 625 370"/><path className="path" d="M107 367 C-22 367 -22 65 107 65"/></Connector><div className="loopNode assign"><h2>맡겨보기</h2><p>어디까지 맡길 수 있을까?</p></div><div className="loopNode review"><h2>결과 살피기</h2><p>어디서, 왜 막혔을까?</p></div><div className="loopNode update"><h2>기준 바꾸기</h2><p>다음에는 무엇을 바꿀까?</p></div><span className="nextLabel">다음 시도</span></div></SlideFrame>},
{title:'나만의 프로젝트 · 3–4주차',note:'마지막 2주에는 각자 필요한 프로젝트를 AI와 함께 만듭니다. 기존 4주 교육과 병행하며, 특히 4주차의 기술·산업 교육을 대체하는 별도 실습 수업이 아닙니다.\n직접 쓸 서비스, 반복 업무를 줄이는 도구, 리서치를 돕는 시스템 등 자신에게 필요한 주제를 고릅니다. 튜터와 완료 기준과 범위를 조정한 뒤 실행합니다. 막힌 결과와 AI에게 내린 지시를 함께 가져오면, 무엇이 어긋났고 다음에는 무엇을 바꿔 맡길지 피드백합니다.\n마지막에는 실제 결과물과 함께 어디까지 AI에게 맡겼고 어디서 직접 판단했는지 공유합니다. 완성도 경쟁보다 큰 일을 맡기고 검토하며 끝까지 시도하는 경험에 초점을 둡니다. 튜터링 횟수·채널·제출 일정은 기수별 운영 안내에서 확정합니다.',render:()=> <SlideFrame label="YOUR OWN PROJECT / WEEK 03–04"><SlideTitle>배운 방법을,<br/><em>내 프로젝트에서 직접 써봅니다.</em></SlideTitle><div className="projectBrief">{[
['무엇을 하나',<>내게 필요한 결과물 하나를 정하고,<br/>마지막 2주 동안 AI와 함께 만듭니다.</>],
['어떤 도움을 받나',<>튜터와 범위를 조정하고, 막힌 원인을 살피며<br/>다음 지시와 검토 방법을 구체화합니다.</>],
['무엇을 남기나',<>직접 보여줄 수 있는 결과물과,<br/>어디까지 맡기고 어디서 개입할지에 대한 나의 기준.</>]
].map(([label,body])=><section key={label}><h2>{label}</h2><p>{body}</p></section>)}</div><p className="projectTakeaway">직접 쓸 서비스 · 업무 도구 · 리서치 시스템 — 내 일에서 출발합니다.</p><span className="projectTiming">4주 교육 중 3–4주차 병행 · 개인 프로젝트 + 튜터 피드백</span></SlideFrame>},
{title:'세션과 기록',note:'개인 계정으로 로그인하고 소속 코호트와 해당 주차를 확인합니다. 장표를 열고, 세션 중의 활동과 논의를 인클래스에 남깁니다.\n리포트가 생성된 뒤에는 세션에서 다룬 내용과 대화를 다시 확인해 다음 시도에 연결합니다.\n세션별 설명·사례·논의 비중은 주제에 맞춰 달라집니다. 기수의 날짜·장소·안내 채널은 확정된 정보만 전달합니다.',render:()=> <SlideFrame label="IN THE SESSION"><SlideTitle>매주 두 시간,<br/>배움과 대화를 기록으로 남깁니다.</SlideTitle><div className="exhibit documents">{[
['시작 전','장표',<>로그인하고<br/>이번 주 자료 열기</>],['세션 중','인클래스',<>배우고, 논의하고<br/>내 생각 남기기</>],['세션 후','세션 리포트',<>대화를 돌아보고<br/>다음 시도에 연결하기</>]
].map(([when,title,body])=><section className="document" key={when}><span className="when">{when}</span><h2>{title}</h2><p>{body}</p></section>)}</div><p className="sessionFacts">4주 · 주 1회 · 회당 2시간</p>{Object.values(window.OT_COHORT||{}).filter(Boolean).length>0&&<p className="cohortFacts">{Object.values(window.OT_COHORT).filter(Boolean).join(' · ')}</p>}</SlideFrame>},
{title:'After Study · 교육 이후의 커뮤니티',note:'교육 이후에는 AI의 최전선에 계속 머무르고자 하는 사람들이 함께 배웁니다. 중요한 것은 정보의 양보다 변화에 대한 해석, 실제 업무를 검토하는 깊이, 서로 기여하는 동료입니다.\n새 모델과 도구의 발표를 그대로 전달하는 데서 멈추지 않고, 직접 써본 경험으로 무엇이 달라졌고 내 활용 방식을 왜 바꿀지 논의합니다. 실제 작업과 결과, 막힌 지점을 함께 살펴 다음 시도를 구체화합니다. 참여자도 자신의 경험과 질문을 가져오고 다른 사람의 고민에 피드백하며 대화의 수준을 높입니다.\n5–6인 소규모, 진행자 1인, 주 1회 약 1시간 온라인 콜을 중심으로 운영합니다. 월 단위 유료 운영 방향이며 시작 일정·구독료·참여 조건은 별도로 안내합니다.',render:()=> <SlideFrame dark label="COMMUNITY"><div className="afterStudyHeading"><span className="afterStudyLabel">AFTER STUDY</span><h1>함께, <em>AI의 최전선에 머무르다.</em></h1></div><p className="communityLead">4주 교육 이후에는, 커뮤니티에서 배움과 경험을 계속 갱신합니다.</p><div className="communityExhibit">{[
['변화의 해석',<>무엇이 달라졌고,<br/>왜 주목해야 할까?</>,<>새 모델·도구를 써본 경험으로<br/>내 일에 중요한 변화를 읽습니다.</>],
['실제 업무의 검토',<>어디까지 맡겼고,<br/>어디서 막혔을까?</>,<>실제 작업·결과·실패를 펼쳐놓고<br/>다음 시도를 함께 구체화합니다.</>],
['기여하는 동료',<>서로의 경험에서,<br/>무엇을 배울 수 있을까?</>,<>자신의 사례와 질문을 가져오고<br/>동료의 고민에 피드백을 더합니다.</>]
].map(([label,question,body])=><section className="communityPillar" key={label}><span className="communityLabel">{label}</span><h2>{question}</h2><p>{body}</p></section>)}</div><div className="communityFooter"><strong>각자의 경험이, 모두의 다음 시도를 바꿉니다.</strong><p>교육 이후 · 주 1회 온라인 콜 · 약 1시간<span>5–6인 소규모 · 진행자 1인</span></p></div></SlideFrame>}
,
{title:'압도적인 역량, 선한 영향력',note:'우리가 지향하는 성장은 나 혼자 일을 잘하게 되는 데서 끝나지 않습니다. AI 시대의 압도적인 인재로 성장하고, 배운 것과 경험을 나누며 주변 사람의 가능성을 넓히는 사람이 되고자 합니다.\n그것이 CREAI+IT EDU가 함께 만들어가려는 선한 영향력입니다.',render:()=> <SlideFrame dark label="OUR AMBITION"><div className="finalStatement"><h1>AI 시대의<br/><em>압도적인 인재로 성장하고,</em></h1><p>그 힘으로 더 많은 사람의 가능성을 열다.</p><span>압도적인 역량, 선한 영향력.</span></div></SlideFrame>}
];
})();
