import type {Report,Evidence,TranscriptPart} from './schema';
import {REPORT_CSS} from './style';
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export type ReportMeta={studyName:string;weekNo:number;date:Date;generatedAt:Date;parts:TranscriptPart[]};
export function renderReport(r:Report,m:ReportMeta){
 const e=escapeHtml,week=m.weekNo===0?'리허설':`${m.weekNo}주차`;
 const refs=(items:Evidence[])=>items.length?`<details class="evidence"><summary>전사 근거 ${items.length}개</summary>${items.map(x=>`<blockquote>녹음 ${m.parts.findIndex(p=>p.id===x.partId)+1}<br>${e(x.quote)}</blockquote>`).join('')}</details>`:'';
 let n=0;const heading=(text:string)=>`<div class="section-head"><span class="num">${String(++n).padStart(2,'0')}</span><h2>${text}</h2></div>`;
 const learning=r.learning.length?`<section>${heading('이번 세션에서 배운 것')}<div class="learnings">${r.learning.map((x,i)=>`<article class="learning-item"><span class="label">Principle ${String(i+1).padStart(2,'0')}</span><h3>${e(x.title)}</h3><p>${e(x.body)}</p>${refs(x.evidence)}</article>`).join('')}</div></section>`:'';
 const activity=r.activity?`<section class="activity"><span class="label">In class<br>함께 진행한 활동</span><div><h3>${e(r.activity.title)}</h3><p>${e(r.activity.body)}</p>${refs(r.activity.evidence)}</div></section>`:'';
 const discussions=r.discussions.length?`<section>${heading('대화에서 더 선명해진 것')}${r.discussions.map((x,i)=>`<article class="discussion"><span class="letter">${String.fromCharCode(65+i)}.</span><div><h3>${e(x.title)}</h3><p>${e(x.context)}</p>${x.proposals.map(p=>`<div class="response"><strong>대화에서 나온 제안</strong><p>${e(p.text)}</p>${refs(p.evidence)}</div>`).join('')}${x.outcome?`<div class="response"><strong>명시적으로 정리된 결론</strong><p>${e(x.outcome)}</p></div>`:''}${x.openQuestion?`<p class="open">남은 질문 — ${e(x.openQuestion)}</p>`:''}${refs(x.evidence)}</div></article>`).join('')}</section>`:'';
 const actions=r.actions.length?`<div class="actions-list">${heading('다음에 시도할 것')}${r.actions.map(x=>`<article class="action"><span class="label">${x.status==='agreed'?'합의된 행동':'시도 제안 · 합의 아님'}</span><p>${e(x.text)}</p>${x.owner||x.due?`<p class="source">${[x.owner&&`담당: ${e(x.owner)}`,x.due&&`기한: ${e(x.due)}`].filter(Boolean).join(' · ')}</p>`:''}${refs(x.evidence)}</article>`).join('')}</div>`:'';
 const questions=r.openQuestions.length?`<div class="questions">${heading('이어갈 질문')}${r.openQuestions.map(x=>`<div><p>${e(x.text)}</p>${refs(x.evidence)}</div>`).join('')}</div>`:'';
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(m.studyName)} · ${week} 세션 리포트</title><style>${REPORT_CSS}</style></head><body><div class="sheet"><div class="mast"><span class="brand">CREAI+IT<span style="color:var(--accent)">.</span></span><span class="label">The study journal / ${e(week)}</span></div><header class="hero"><div><div class="label">${e(m.studyName)} · ${m.date.toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} · Session report</div><h1>${e(r.title)}</h1><p>${e(r.subtitle)}</p></div><div class="issue">${m.weekNo===0?'R':String(m.weekNo).padStart(2,'0')}<small>${e(week)}</small></div></header><div class="intro"><span class="label">이번 세션의 핵심</span><div><p>${e(r.overview)}</p>${refs(r.overviewEvidence)}</div></div><main>${learning}${activity}${discussions}${actions||questions?`<section class="bottom">${actions}${questions}</section>`:''}${r.limitations.length?`<section class="limitations"><h3>기록의 한계</h3>${r.limitations.map(x=>`<p>${e(x)}</p>`).join('')}</section>`:''}</main><footer class="foot"><span>세션 녹음 전사본 기반 자동 생성 · 원본 녹음과 함께 확인해 주세요.<br>생성 ${m.generatedAt.toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</span><span>CREAI+IT AI STUDY<br>${e(m.studyName)} · ${e(week)}</span></footer></div></body></html>`;
}
