BEGIN;
CREATE TABLE "StudyMembership" (
 "studyId" TEXT NOT NULL REFERENCES "Study"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("studyId","userId")
);
CREATE INDEX "StudyMembership_userId_idx" ON "StudyMembership"("userId");
ALTER TABLE "StudyMembership" ENABLE ROW LEVEL SECURITY;
COMMIT;
